name: Validate

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  test:

    name: Unit and e2e tests

    timeout-minutes: 60

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: lts/hydrogen

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: latest

      - name: Cache deps dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-clojure-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-clojure

      - name: Install dependencies for unit tests
        run: npm ci

      - name: Unit tests
        run: ./bin/kaocha

      - name: Install dependencies
        working-directory: ./playwright
        run: npm ci

      - name: Install Playwright Browsers
        working-directory: ./playwright
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        working-directory: ./playwright
        run: npm test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright/playwright-report/
          retention-days: 30
